# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Deliver Safe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Deliver Safe
  
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'lottie-ios'
  pod 'LocationPicker'

end
